package entity;

public class Student {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.Id
     *
     * @mbg.generated Wed Sep 05 16:36:42 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.UserName
     *
     * @mbg.generated Wed Sep 05 16:36:42 CST 2018
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.Password
     *
     * @mbg.generated Wed Sep 05 16:36:42 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.Age
     *
     * @mbg.generated Wed Sep 05 16:36:42 CST 2018
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.Address
     *
     * @mbg.generated Wed Sep 05 16:36:42 CST 2018
     */
    private String address;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.Id
     *
     * @return the value of t_student.Id
     *
     * @mbg.generated Wed Sep 05 16:36:42 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.Id
     *
     * @param id the value for t_student.Id
     *
     * @mbg.generated Wed Sep 05 16:36:42 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.UserName
     *
     * @return the value of t_student.UserName
     *
     * @mbg.generated Wed Sep 05 16:36:42 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.UserName
     *
     * @param username the value for t_student.UserName
     *
     * @mbg.generated Wed Sep 05 16:36:42 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.Password
     *
     * @return the value of t_student.Password
     *
     * @mbg.generated Wed Sep 05 16:36:42 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.Password
     *
     * @param password the value for t_student.Password
     *
     * @mbg.generated Wed Sep 05 16:36:42 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.Age
     *
     * @return the value of t_student.Age
     *
     * @mbg.generated Wed Sep 05 16:36:42 CST 2018
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.Age
     *
     * @param age the value for t_student.Age
     *
     * @mbg.generated Wed Sep 05 16:36:42 CST 2018
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.Address
     *
     * @return the value of t_student.Address
     *
     * @mbg.generated Wed Sep 05 16:36:42 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.Address
     *
     * @param address the value for t_student.Address
     *
     * @mbg.generated Wed Sep 05 16:36:42 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }
}